[package]
name = "internet_monitor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ping = "0.3.0"
rand = "0.7"
sudo = "0.6.0"
chrono = "0.4.19"